---
title: "her2st_breast_cancer"
author: "asif zubair"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.height=8, fig.width=12)
```


```{r}
library(purrr)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(ggExtra)
library(ggcorrplot)
library(magick)
source("../utils/st_helpers.R")
source("../utils/her2st_helpers.R")

## make export directory
if (!file.exists("export/fig4")) {
  dir.create("export/fig4", recursive = T)
}
```


## Data

```{r}
## raw cleaned image
raw_img = image_read("data/fig4/HE_BT23903_C2a_edited.jpg")

## transaparent image
path_img1 = "data/fig4/HE_BT23903_C2a_edited_transparent_outline_black.jpg"
img1 = image_read(path_img1)

## pathologist ground truth
path_gt1 = loadHer2stLbl("data/fig4/G2_labeled_coordinates.tsv")

# tissue locations
tp_img1 = loadHer2stTP("data/fig4/G2_selection.tsv")

## DL predictions - patch level
pred_f = "data/fig4/prediction-G1"
dl_pred_ptch <- read_dl_pred_ptch(pred_f)
dl_pred_ptch <- dl_pred_ptch %>% filter(x >= 100) %>% filter(x <= 8500) %>% filter(y >= 1165) %>% filter(y <= 7264)

## DL predictions - spot level
dl_pred_img1 = readRDS("data/fig4/g2_til_mapped_decon_k10d10_sct.rds")

## Decon predicitons
decon_img1 = loadHer2stProp("data/fig4/results_mega_slide_g2_k10d10_sct.rds")

## P-value for improvement over base model
o <- readRDS("data/fig4/g2_pval_median_summary.rds")

## GIST enhanced-model with prior on proportions
decon_gist = loadHer2stProp("data/fig4/results_baycon_base_decon_stdata_mega_slide_g2_k10d10_noFilter_sct_beta_prior_mapped_probabilities_lambda_50_tnbc_sigmat_sct.rds")
```


## Plots

## (A)

```{r}
## raw image

```


## (B) 

```{r, fig.height=12, fig.width=15}
## Representative H&E stained pathology image highlighting spatial transcriptomics spots that were annotated as being in a regions of immune cell infiltrate, by a previous pathologist.
path_gt1 <- path_gt1 %>% 
  tibble::rownames_to_column("spot") %>%
  mutate(label = ifelse(label == "immune infiltrate", "Immune", "Non-Immune")) %>% 
  tibble::column_to_rownames("spot") 
p <- plot_lbls_on_img(img1, path_gt1, tp_img1, 0.6, alpha = 1) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.08, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE)
ggsave(filename="export/fig4/02_g1_path_anno.png", plot=p, height=2, width=2.3, units=c("in"), dpi=600)
```


## (C) 

```{r}
## Representative pathology slide image of one of the breast tumors with deep learning predictions for immune cells (at patch level).
p <- plot_dl_ptch_on_img(img1, dl_pred_ptch, shape = 15, size = 0.25) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE)
ggsave(filename="export/fig4/03_ptch_til_on_g1_new_coordinates.png", plot=p, height=2.15, width=2.3, units=c("in"), dpi=600)
```


## (D) 

```{r, fig.height=12, fig.width=15}
## Representative pathology slide image of one of the breast tumors with deep learning predictions for immune cells (at spot level).
p <- plot_dl_pred_on_img(img1, dl_pred_img1, tp_img1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE) 
ggsave(filename="export/fig4/04_til_on_g1.png", plot=p, height=2.15, width=2.3, units=c("in"), dpi=600)
```


## (E) 

```{r, fig.height=12, fig.width=15}
## Representative Base deconvolution predictions for immune cells on the same slide as above
p <- plot_decon_pred_on_img(img1, decon_img1, tp_img1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE) + 
  scale_colour_gradient(low="#f8d39f", high="#800000", limits=c(0, 0.46))
ggsave(filename="export/fig4/05_base_decon_on_g1.png", plot=p, height=2.15, width=2.3, units=c("in"), dpi=600)
```


## (F) 

```{r}
## Scatterplot summarizing all improvements etc.
f <- function(base_df, compare_df, metric = "ratio", cell_types = "tcell.bcell", ylab, size_m = 2){
  df1 <- base_df %>% 
    tidyr::gather("metric", "value", -celltype, -summary, -slide) %>% 
    tidyr::separate(slide, c("prior", "slide"), "_")
  df2 <- compare_df %>% 
    tidyr::gather("metric", "value", -celltype, -summary, -slide) %>% 
    tidyr::separate(slide, c("prior", "slide"), "_")
  inner_join(df1, df2, by = c("celltype", "summary", "slide", "metric")) %>% 
    filter(metric == !!rlang::enquo(metric)) %>%
    filter(celltype %in% cell_types) %>%
    ggplot(aes(x = value.x, y = value.y)) +
    geom_point(aes(color = slide, shape = summary), size = size_m) +
    geom_abline(slope = 1, intercept = 0, color = "red", size = 0.2) +
    xlab("base_deconvolution") +
    ylab(paste("prior:", ylab)) +
    ggtitle(paste("ratio", cell_types, ylab, sep = "|"))
}

## get pathology annotations
slides = c("a1", "d1", "e1", "f1", "g2", "h1")
path_lbls_f = paste0("data/fig4/", toupper(slides), "_labeled_coordinates.tsv")
path_lbls = map(set_names(path_lbls_f, slides), 
                ~loadHer2stLbl(.x) %>% rename(path_lbl = label))

## base results
result_file = paste0("data/fig4/results_mega_slide_", slides, "_k10d10_sct.rds")
base_results = map(set_names(result_file, paste0("base_", slides)), loadHer2stProp)
base_df_immune <- map2(base_results, path_lbls, get_ratio_metric)  %>% 
  imap(function(.x, .y){.x$slide = .y; .x}) %>% 
  bind_rows() %>% 
  filter(summary == "median")

## raw results
compare_name = "mapped_"
ylabel = "mapped_probabilities"
compare_results_f = paste0("data/fig4/results_baycon_base_decon_stdata_mega_slide_", slides, 
                       "_k10d10_noFilter_sct_beta_prior_mapped_probabilities_lambda_50_tnbc_sigmat_sct.rds")
compare_results = map(set_names(compare_results_f, paste0(compare_name, slides)), loadHer2stProp)
compare_df_immune <- map2(compare_results, path_lbls, ~get_ratio_metric(.x, .y, spot_type = "immune"))   %>% 
  imap(function(.x, .y){.x$slide = .y; .x}) %>% 
  bind_rows() %>%
  filter(summary == "median")

p <- f(base_df_immune, compare_df_immune, metric = "ratio", cell_types = "tcell.bcell", ylab = ylabel, size_m = 1.3) +
  guides(size = FALSE, shape = FALSE)  +
  theme(
    legend.position = c(0.2, 0.95),
    legend.key.size = unit(0.1, 'in'),
    legend.key = element_rect(colour = "white", fill = "white"),
    legend.title = element_blank(),
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.box.background = element_rect(colour = "black", size = 0.1, linetype = 1),
    legend.box.margin = margin(0,0,0,0),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_rect(fill = "white", colour = "white"),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.line = element_line(colour="black", size = 0.3),
    axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
    axis.title = element_text(family="Arial", face="plain", size=8)) +
  xlab("Ratio correctly assigned (expression only)") + 
  ylab("Ratio correctly assigned (GIST)") +
  ggtitle("") +
  guides(color = guide_legend(ncol=2)) +
  scale_color_manual(labels = c("A1", "D1", "E1", "F1", "G1", "H1"), values = c(paste0("#", c("e41a1c", "377eb8", "4daf4a", "984ea3", "ff7f00", "ffff33"))) )
ggsave(filename = "export/fig4/06_scatterplot_all_slides.svg", plot=p, height=2, width=2.5, units = c("in"), dpi=300)
```


## (G) 

```{r}
## Histogram
p <- ggplot(mapping = aes(o$permDiff)) +
    geom_histogram(bins = 100, color = "darkblue") + 
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(), 
      panel.background = element_rect(fill = "white", colour = "white"),
      axis.ticks = element_line(colour = "black", size = 0.1),
      axis.line = element_line(colour="black", size = 0.3),
      axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
      axis.title = element_text(family="Arial", face="plain", size=8)) +
    xlab("Permuted test statistic") +
    ylab("Count") +
    geom_vline(xintercept = o$observedDiff, color = "red", size = 0.2)
ggsave(filename="export/fig4/07_pval_for_g2.svg", plot=p, height=2, width=2.3, units=c("in"), dpi=300)
```


## (H) 

```{r}
## GIST-based image
p <- plot_decon_pred_on_img(img1, decon_gist, tp_img1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE) + 
  scale_colour_gradient(low="#f8d39f", high="#800000", limits=c(0, 0.46))
ggsave(filename="export/fig4/08_gist_on_g1.png", plot=p, height=2.15, width=2.3, units=c("in"), dpi=600)
```

