---
title: "fig5_pathologist_reannotation"
author: "asif zubair"
date: "8/11/2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.height=8, fig.width=12)
```


```{r}
library(purrr)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(ggExtra)
library(ggcorrplot)
library(magick)
library(imager)
source("../utils/st_helpers.R")
source("../utils/her2st_helpers.R")

## make export directory
if (!file.exists("export/fig5")) {
  dir.create("export/fig5", recursive = T)
}
```


## Data

```{r}
## Slide H1
img_h1 = image_read("data/fig5/HE_BT24044_D2_edited_transparent_outline_black.jpg")
tp_h1 = loadHer2stTP("data/fig5/H1_selection.tsv")
decon_prior_h1 = loadHer2stProp(
  "data/fig5/results_baycon_base_decon_stdata_mega_slide_h1_k10d10_noFilter_sct_beta_prior_mapped_probabilities_lambda_50_tnbc_sigmat_sct.rds")

# re-annotation
table_h1 = readRDS("data/fig5/table_H1.rds") 
o = readRDS("data/fig5/path_annotation_H1.rds")
a = readRDS("data/fig5/path_images_H1.rds")


## Slide B1
img_b1 = image_read("data/fig5/BT10737_C1_HE_edited_transparent_outline_black.jpg")
decon_base_b1 = loadHer2stProp("data/fig5/results_mega_slide_b1_k10d10_sct.rds")
dl_pred_b1 = readRDS("data/fig5/b1_til_mapped_decon_k10d10_sct.rds")
decon_prior_b1 = loadHer2stProp(
  "data/fig5/results_baycon_base_decon_stdata_mega_slide_b1_k10d10_noFilter_sct_beta_prior_mapped_probabilities_lambda_50_tnbc_sigmat_sct.rds")
tp_b1 = loadHer2stTP("data/fig5/B1_selection.tsv")

# re-annotation
table_b1 = readRDS("data/fig5/table_B1.rds") 
```


## Plots


## (A) 

```{r}
## GIST model output, but drawing a blue box around spots that were annotated as “immune infiltrate” by first pathologist.
p <- plot_decon_pred_on_img(img_h1, decon_prior_h1, tp_h1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE) 
ggsave(filename="export/fig5/01_gist_on_h1.png", 
       plot=p, height=2.15, width=2.3, units = c("in"), dpi=600)
```


## (B) 

```{r}
## Three representative 100 x 100 micron subimages from previous pathologist annotated region (top), other high confidence regions from GIST model (middle) and randomly selected regions (bottom).
read_plt <- function(barcodes){
  img_pths = map(barcodes, ~file.path(img_dir, paste0(.x, ".png")))
  imgs = map(img_pths, ~load.image(.x))
  walk(imgs, ~print(plot(.x, axes = F)))
}

img_dir = "data/fig5"
annotated = c("14x25", "16x25", "18x20")
outlier = c("14x20", "16x34", "7x25")
random = c("16x22", "12x11", "16x11")

png(file="./export/fig5/02_rep_spots.png", 
    res=900, width=1350, height=1400, pointsize=10,
		type="cairo", antialias="default")
  par(mfrow = c(3,3))
  par(mar=c(0.1, 0, 0.1, 0))
  read_plt(annotated)
  read_plt(outlier)
  read_plt(random)
dev.off()
```


## (C) 

```{r}
## Dot plot representation of the results of 2nd pathologists reannotation for slide H1.
colnames(table_h1) <- c("Annotated", "GIST", "Random")
rownames(table_h1) <- c("Low", "Middle", "High")
table_h1 = table_h1 %>% as.data.frame()
p <- make_dot_plot2(table_h1) + 
  guides(size=F) +
  theme(legend.key.size = unit(0.1, 'in'),
    legend.key = element_rect(colour = "white", fill = "white"),
    legend.title = element_text(family="Arial", face="plain", size=8),
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.box.background = element_rect(colour = "white"),
    legend.box.margin = margin(0,0,0,0),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_rect(fill = "white", colour = "white"),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.line = element_line(colour="black", size = 0.3),
    axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(family="Arial", face="plain", size=8, colour="black")) + 
  labs(color = "Number\n of spots") +
  ylab("2nd pathologist's\n immune cell score") +
  scale_colour_gradient(low="#a8ddb5", high = "#43a2ca")
ggsave(filename="export/fig5/03_dot_plot_h1.svg", 
       plot=p, height=2, width=2.5, units=c("in"), dpi=300)
```


## (D) 

```{r}
## ASSOCIATION BETWEEN QUANTITATIVE GIST SCORES AND PATHOLOGIST LOW-MIDDLE-HIGH ANNOATION - slide H1
df = purrr::reduce(list(decon_prior_h1 %>% tibble::rownames_to_column("barcode"), o, a), function(x, y) merge(x, y, by = "barcode"))
p <- df %>% 
  ggplot(aes(y = tcell.bcell, 
             x = forcats::fct_recode(forcats::fct_relevel(label, c("low", "medium", "high")), Low="low", Middle="medium", High="high"), 
             fill = type)) +
  geom_boxplot(position = position_dodge(1), lwd = 0.1, outlier.size = 0.01) +
  xlab("path_score") +
  theme(legend.key.size = unit(0.1, 'in'),
    legend.key = element_rect(colour = "white", fill = "white"),
    legend.title = element_blank(),
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.box.background = element_rect(colour = "white"),
    legend.box.margin = margin(0,0,0,0),
    legend.position = "bottom",
    legend.direction = "horizontal",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_rect(fill = "white", colour = "white"),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.line = element_line(colour="black", size = 0.3),
    axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
    axis.title = element_text(family="Arial", face="plain", size=8)) + 
  ylab("GIST score") +
  xlab("2nd pathologist's score") +
  scale_fill_manual(values = c("#fee0d2", "#fff7bc", "#99d8c9"), labels = c("Annotated", "GIST", "Random")) +
  rotateTextX()
ggsave(filename="export/fig5/04_gist_score_annotation_h1.svg", 
       plot=p, height=2.3, width=2.5, units=c("in"), dpi=300)
```


## (E) 

```{r}
## GIST base model output for slide B1.
p <- plot_decon_pred_on_img(img_b1, decon_base_b1, tp_b1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  scale_colour_gradient(low="#f8d39f", high = "#800000", limits = c(0, 0.75)) +
  guides(size = FALSE, alpha = FALSE) 
ggsave(filename="export/fig5/05_gist_base_on_b1.png", 
       plot=p, height=2.15, width=2.3, units = c("in"), dpi=600)
```


## (F) 

```{r}
## Deep learning based prediction for slide B1
p <- plot_dl_pred_on_img(img_b1, dl_pred_b1, tp_b1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),    
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +
  guides(size = FALSE, alpha = FALSE) 
ggsave(filename = "export/fig5/06_til_on_b1.png", 
       plot=p, height=2.15, width=2.3, units = c("in"), dpi=600)
```


## (G) 

```{r}
## Per-spot correlation between GIST base model and deep learning-based predictions for slide B1.
p <- merge(dl_pred_b1, decon_base_b1 %>% select(tcell.bcell), by = 0) %>% 
  tibble::column_to_rownames("Row.names") %>% 
  ggplot(aes(x = tcell.bcell, y = out)) +
  geom_point(size = 0.1) +
  ggpubr::stat_cor(method='spearman', cor.coef.name = 'rho', size = 3, 
                   label.x.npc = 'left', label.y.npc = 'top') +
  geom_smooth(method = "lm", level=0, color = "red", size = 0.2) + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_rect(fill = "white", colour = "white"),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.line = element_line(colour="black", size = 0.3),
    axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
    axis.title = element_text(family="Arial", face="plain", size=8)) +
  xlab("Gene expression-derived\n immune cell proportions")+ 
  ylab("Deep learning-derived\n immune cell proportions")
ggsave(filename="export/fig5/07_corr_til_decon_on_b1.svg", 
       plot=p, height=2, width=2.3, units=c("in"), dpi=300)  
```


## (H) 

```{r}
## GIST model-based prediction for slide B1.
p <- plot_decon_pred_on_img(img_b1, decon_prior_b1, tp_b1, 0.6) +
  theme(
    legend.box.margin = margin(5.25,14,5.25,14),    
    legend.key.width = unit(0.25, "in"),
    legend.key.height = unit(0.06, "in"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.title = element_blank(),
    title = element_text(family="Arial", face="plain", size=8),
    plot.title = element_text(hjust = 0.5),
  ) +     
  scale_colour_gradient(low="#f8d39f", high = "#800000", limits = c(0, 0.75)) +
  guides(size = FALSE, alpha = FALSE) 
ggsave(filename="export/fig5/08_gist_on_b1.png", 
       plot=p, height=2.15, width=2.3, units=c("in"), dpi=600)
```


## (I) 

```{r}
## Dot plot representation of the results of 2nd pathologists reannotation for slide B1
colnames(table_b1) <- c("GIST", "Random")
rownames(table_b1) <- c("Low", "Middle", "High")
table_b1 = table_b1 %>% as.data.frame()
p <- make_dot_plot2(table_b1) + 
  guides(size=F) +
  theme(legend.key.size = unit(0.1, 'in'),
    legend.key = element_rect(colour = "white", fill = "white"),
    legend.title = element_text(family="Arial", face="plain", size=8),
    legend.text = element_text(family="Arial", face="plain", size=8),
    legend.box.background = element_rect(colour = "white"),
    legend.box.margin = margin(0,0,0,0),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_rect(fill = "white", colour = "white"),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.line = element_line(colour="black", size = 0.3),
    axis.text = element_text(family="Arial", face="plain", size=8, colour="black"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(family="Arial", face="plain", size=8, colour="black")) + 
  ylab("2nd pathologist's\n immune cell score") +
  labs(color = "Number\n of spots") +
  scale_colour_gradient(low="#a8ddb5", high = "#43a2ca")
ggsave(filename="export/fig5/09_dot_plot_b1.svg", 
       plot=p, height=2, width=2.25, units=c("in"), dpi=300)
```

